---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: chieh-cluster
  region: ap-southeast-1
  version: "1.17"

nodeGroups:
  - name: chieh-linux
    instanceType: t2.micro
    desiredCapacity: 3
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
